classDiagram
    namespace Cubies {
        class Corners {
            - prm: [usize; 8]
            - ori: [usize; 8]
            + twisted(twist) [28 ns]
            + rotated_colours(rot) [56 ns]
            + from_indices(prm, ori) [78 ns]
            + prm_index() [8 ns]
            + ori_index() [6 ns]
        }
        class Edges {
            - prm: [usize; 12]
            - ori: [usize; 12]
            + twisted(twist) [32 ns]
            + rotated_colours(rot) [82 ns]
            + from_indices(slice_prm, non_slice_prm, slice_loc_index, ori) [216 ns]
            + slice_prm_index() [21 ns]
            + non_slice_prm_index() [24 ns]
            + slice_loc_index() [26 ns]
            + ori_index() [4 ns]
        }
    }
    namespace Indices {
        class CornersCube {
            - c_prm
            - c_ori
            + from_index(idx)
            + index()
            + combine_indices(prm, ori)
        }
        class SubsetCube {
            - c_prm
            - e_slice_prm
            - e_non_slice_prm
            + from_index(idx)
            + index()
            + is_solved()
        }
        class CosetCube {
            - c_ori
            - e_ori
            - e_slice_loc
            + from_index(idx)
            + index()
            + in_subset()
        }
    }

    class Twister {
        + twisted_c_ori(c_ori, twist) usize
        + twisted_c_prm(c_prm, twist) usize
        + twisted_e_slice_prm(e_slice_prm, e_slice_loc, twist) usize
        + twisted_e_non_slice_prm(e_non_slice_prm, e_slice_loc, twist) usize
        + twisted_e_slice_loc(e_slice_loc, twist) usize
        + twisted_e_ori(e_ori, twist) usize
    }
    Twister ..> Corners
    Twister ..> Edges

    class DistanceTable {
        + distance(idx)
    }
    DistanceTable ..> CornersCube
    DistanceTable ..> SubsetCube
    DistanceTable ..> CosetCube
    DistanceTable ..> Twister

    class DirectionTable {
        + distance(idx)
        + less_distance(idx) TwistSet
        + more_distance(idx) TwistSet
    }
    DirectionTable ..> DistanceTable
    DirectionTable ..> CosetCube

    class TwoPhaseSolver {
        + solve(cube) Twists
    }
    TwoPhaseSolver ..> DistanceTable
    TwoPhaseSolver ..> DirectionTable
